_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./object_detection/weights/model_final_b275ba.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 2